### ISSUE TITLE
make an example c++ with your method's

### ISSUE THREAD

**Issue by Axe-Usa** [hfiref0x/UACME#10]
Hi it's possible to make a simple int main application and use one of these methods like simda etc.. to elevate privilages in my main program? with your project? It looks like very good the project in this case you are using like a loader i think? Maybe the only way is to use this loader separately ? or including in one program made in c++/c or which language? it's to check and learn more these methods.

**Comment by hfiref0x** [comment]
Take the method you want - understand what (and how) it does and reproduce then on whatever compilable language you want. I'm not going to code any examples because this project is example itself.
