### ISSUE TITLE
How to make current process load comctl32.dll in method 22

### ISSUE THREAD

**Issue by tconqueror** [hfiref0x/UACME#101]
I'm trying to implement method 22 and want to ask for your help.
My problem is the title, the process don't load the comctl32. I added the manifest file like what you did, and checked it inside the enumerate callback function and realized that the module wasn't load. Can you give me suggestions. Thanks!!!

**Comment by hfiref0x** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/commctrl/nf-commctrl-initcommoncontrols

**Comment by tconqueror** [comment]
Thank you! It worked =))
