### ISSUE TITLE
Are there anyways to Disable Wow64Redirection when use IFileOperation interface?

### ISSUE THREAD

**Issue by tconqueror** [hfiref0x/UACME#102]
I get into problem when trying to copy some x64 DLL into system32 from x86 process. Are there anyways to disable Wow64Redirection when use IFileOperation interface? I tried [Wow64DisableWow64FsRedirection](https://docs.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-wow64disablewow64fsredirection) but it didn't work.
Thank you!

**Comment by hfiref0x** [comment]
This is clearly not an issue of this repository.
