### ISSUE TITLE
Error C2440 while compiling test.c

### ISSUE THREAD

**Issue by captain-woof** [hfiref0x/UACME#105]
Building the Akagi project gives me this error:
Error C2440 'function': cannot convert from 'void (__cdecl *)(PUSER_ASSOC_SIGNATURE,PVOID,BOOLEAN *)' to 'PSUP_UAS_ENUMERATION_CALLBACK_FUNCTION' in the C:\Users\<redacted>\source\repos\UACME\Akagi\tests\test.c file.

**Comment by hfiref0x** [comment]
Not reproducible.
