### ISSUE TITLE
IDL files?

### ISSUE THREAD

**Issue by pat-ux** [hfiref0x/UACME#107]
Hi, could you include the IDL files for the RPC interfaces in the VS project, or post the command to generate?

**Comment by hfiref0x** [comment]
IDL file is in Source/Akagi/appinfo.

**Comment by pat-ux** [comment]
Ok. Do you know if the process has to appear to be explorer.exe to access the appinfo rpc server asynchronously? Regular it works, like from forshaw, but asynchronous, it may do access check?

**Comment by hfiref0x** [comment]
I don't see how your question is related to this rep.

**Comment by pat-ux** [comment]
the answer to the question is yes, explorer.exe is able to call RPC async, random process is not.
