### ISSUE TITLE
Question: Is it possible to include all of the required vcredist dlls into the build so it can be used on a new pc?

### ISSUE THREAD

**Issue by TungstenWolf** [hfiref0x/UACME#108]
As the title asks: Is it possible to include all of the required vcredist dlls into the build so it can be used on a new pc? The pc im working with cant install vcredist right now, and if this was to be used on some other pc in the future, if they didnt have vcredist you wouldnt be able to use this at all. If this is possible, then how would one do this? i have tried including the dlls in the build, but it still requires them to be installed to system32. I would think that you could somehow build the project with the dlls packed in, but i do not see a way to do that.

**Comment by hfiref0x** [comment]
This project does not use VC runtime. If your compiled binary use it then you compiled it wrong.

**Comment by TungstenWolf** [comment]
I will try to re compile it tomorrow, I simply downloaded the entire source folder and just hit build on akagi, is this not what I was supposed to do? I dont work much with c++ and c# so compiling is a little odd for me

**Comment by hfiref0x** [comment]
This project kind of assume you are familiar with Visual Studio at least at beginner level.

**Comment by TungstenWolf** [comment]
I am familiar with beginner level, I just do compile a lot of stuff, i usually use it for writing code for unity

**Comment by TungstenWolf** [comment]
So I may be retarded. I am going back and looking at steps, and I see that you need to undefine KUMA_STUB which I don't know what that is or how to do it. Then you are supposed to encrypt all of the payload units after the compilation, but idk how to encrypt, I also don't know how to "generate secret blobs for these units using Naka module" although I'm sure it will make more sense after the other steps. I will look these up, and test them, and if I get them figured out I will just close this issue. Thanks for the help so far

**Comment by TungstenWolf** [comment]
Ok so i am retarded. i am looking at it and you are totally right, i just forgot to switch to release version. im a dumbass.
