### ISSUE TITLE
Question: How to use naka?

### ISSUE THREAD

**Issue by TungstenWolf** [hfiref0x/UACME#109]
Hey its me again, i am going though all of you directions, and i can not figure out for the love of me how to use the naka module. First, i dont know how you can just execute a module in Visual Studio. I am just running the Naka.exe and dragging akagi .exe and its folder both onto the program for it to run and there is nothing. Even if i do it in cmd, still nothing. I thought its supposed to encrypt and move the files to bin like you said in your comment, but it just doesnt. Any help with this? i feel like the directions could be a little more detailed, but that could just be me.

**Comment by hfiref0x** [comment]
1. Compile it.
2. Run it from command line as **naka path_to_payload.dll** where payload.dll is one of the compiled uacme dlls (fubuki, akatsuki etc), e.g. C:\test\naka.exe C:\test\dll\fubuki64.dll
3. run **naka --stable** to generate secrets table which is required by Akagi for AES decryption
4.  Copy result files (they will have same name as input dll but with cd file extension) to Akagi\Bin folder, move secrets files (secrets32.cd and secrets64.cd) here too.
5. Rebuild Akagi with full recompilation.

**Comment by TungstenWolf** [comment]
Thanks so much
