### ISSUE TITLE
UAC bypass mitigation

### ISSUE THREAD

**Issue by abulyaev** [hfiref0x/UACME#110]
Hi
I'm wondering if there is some way to mitigate elevated COM objects uac bypass? For example methods 65 and 66.

**Comment by hfiref0x** [comment]
1. Remove those interfaces from COMAutoApprovalList. This will trigger UAC window at elevation attempt
2. Set UAC level to AlwaysNotify
3. Account without administrator privileges

**Comment by zacchi4k** [comment]
Out of curiosity, would a separate admin account without a password suffice? Testing it seems to confirm it is, but I wonder if it could be circumvented with the account not having a pw

**Comment by hfiref0x** [comment]
Yes.

**Comment by zacchi4k** [comment]
> Yes. Separate non-admin account you mean.

No, separate admin account without password. Technically with that setup uacme doesn't work, stuff like tasks requiring admin break, and the UAC asks for a password, which happens to be empty, but again I wonder if the password being empty is an issue or what matters is only the separation
