### ISSUE TITLE
Error when running Naka32.exe --stable

### ISSUE THREAD

**Issue by paradoxsupreme** [hfiref0x/UACME#112]
I am getting a `File read error, memory not allocated` when I try to run `Naka32.exe --stable`. What am I doing wrong? Does it need any parameters? Apart from that how I can compile `kamikaze `?

**Comment by hfiref0x** [comment]
The *.key files generated by naka previous run without --stable must exist in the same directory. Kamikaze is MMC snap-in, it is a text file and not compilable.

Apparently I answered somewhat similar Naka question before here https://github.com/hfiref0x/UACME/issues/109

**Comment by paradoxsupreme** [comment]
The `.key` files are all in the same directory with `Naka32.exe` and I run `Naka32.exe --stable` and I get `File read error, memory not allocated`. Do I need to pass the `key `files as parameters like so `Naka32.exe --stable Akatsuki64.exe Fubuki32.exe Fubuki64.exe Kamikaze.exe`? Also I copy Kamikaze.msc in the `Akagi/bin` folder as is am I right?

**Comment by hfiref0x** [comment]
It expects these files
Akatsuki64.key
Fubuki64.key
Kamikaze.key
Fubuki32.key

if any of them are missing it will show you that message.

**Comment by paradoxsupreme** [comment]
None is missing. They are all in the same folder (Source/Naka/output/Win32/Debug) as Naka32.exe

**Comment by hfiref0x** [comment]
Depends how you launch it. It looks for files in process current directory.

**Comment by waiwaiwai** [comment]
hi, i got all the key files existing in the same but still got "File read error, memory not allocated", may i know why i am missing?

running visual studio2022, v143 in VM with 4G RAM.
already compile and has the result below:
![image](https://user-images.githubusercontent.com/31471002/153913994-7a582dca-c762-4555-b2e5-daa07fd58ffe.png)
under the same folder with naka32.exe

Please advise, thanks!
