### ISSUE TITLE
Build Error: StripDebug.exe"

### ISSUE THREAD

**Issue by JohnNash99** [hfiref0x/UACME#12]
Error	2	error MSB3073: The command "\Utils\StripDebug.exe .\output\Win32\Release\Akagi32.exe

But Where is the "\Utils\StripDebug.exe" ?

**Comment by hfiref0x** [comment]
Go to Project -> Akagi Properties -> Build Events -> Post Build Event, Use In Build set to No.

**Comment by servomekanism** [comment]
6>  Naka.vcxproj -> C:\XXX\Documents\Visual Studio 2015\XXX\UACME\Source\Naka\.\output\x64\ReleaseInternal\Naka64.exe
6>  The system cannot find the path specified.
6>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "\Utils\StripDebug.exe .\output\x64\ReleaseInternal\Naka64.exe
6>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 3.

The build completes with 5 succeeded and one error which is the one above.
