### ISSUE TITLE
"File read error, memory not allocated" when running Naka32.exe with all key existing.

### ISSUE THREAD

**Issue by waiwaiwai** [hfiref0x/UACME#121]
hi, i got all the key files existing in the same but still got "File read error, memory not allocated", may i know what i am missing?

running visual studio2022, v143 on win10 in VM with 4G RAM.
already compile and has the result below:
![image](https://user-images.githubusercontent.com/31471002/153914295-27875a90-16cc-44f2-bc43-506544c2d344.png)

under the same folder with naka32.exe

Please advise, thanks!

**Comment by hfiref0x** [comment]
It obviosly won't work for you in debug build, https://github.com/hfiref0x/UACME/blob/master/Source/Naka/main.c#L1098-L1100

**Comment by waiwaiwai** [comment]
hi hfiref0x,

Thanks a lot for your hints! it works for me now!
Thank You Very Much!
