### ISSUE TITLE
Port to python3

### ISSUE THREAD

**Issue by jiaop5** [hfiref0x/UACME#122]
Will it be possible to port this code to python 3?

**Comment by jiaop5** [comment]
What methods can be transferred?

**Comment by hfiref0x** [comment]
The most easiest - for example most of registry hijacks.

**Comment by jiaop5** [comment]
Is this module working today?

**Comment by hfiref0x** [comment]
There is nothing written in python in this rep and won't be. It is all up to you or someone else who wants to do this.
