### ISSUE TITLE
Maybe method 63 and 71 can't run successfully

### ISSUE THREAD

**Issue by GUANCAIBAN** [hfiref0x/UACME#124]
I run the akagi64.exe,but no something append.It is my issue? command is as follow:
`
.\Akagi64.exe 63 cmd.exe
.\Akagi64.exe 71 cmd.exe
`

**Comment by hfiref0x** [comment]
If you didn't followed https://github.com/hfiref0x/UACME#instructions then executable you compiled is invalid and will not work properly with most of methods.

**Comment by GUANCAIBAN** [comment]
Thanks for your answer。
