### ISSUE TITLE
New UacBypass  

### ISSUE THREAD

**Issue by GUANCAIBAN** [hfiref0x/UACME#125]
follow it:
https://www.tiraniddo.dev/2022/03/bypassing-uac-in-most-complex-way.html

**Comment by hfiref0x** [comment]
There is no working sample provided and digging into Delpy kekeo code is the last thing I want to do. You can built a working sample of this technique, share it and then I maybe add it. However I would not give you any guarantee of that or guarantee that this repository will be available at that time.
