### ISSUE TITLE
UAC Bypass via IDiagnosticProfile COM Interface

### ISSUE THREAD

**Issue by Ruuucker** [hfiref0x/UACME#130]
Hi, I come across this: https://github.com/Wh04m1001/IDiagnosticProfileUAC
Seems like a new method to move arbitrary file as Administrator via SaveDirectoryAsCab method of IDiagnosticProfile. Which is interesting bc majority of UAC bypasses uses IFileOperation\ISecurityEditor.
The second part is also new, it uses wow64log.dll and Edge. Take a look.

**Comment by hfiref0x** [comment]
Hello,

what is the availability of this IDiagnosticProfile COM interface?

**Comment by Ruuucker** [comment]
It presents starting from Windows 7 and the latest version I got is Win10 build 19041 which is also having it.

**Comment by hfiref0x** [comment]
Do you have proper definition of IDiagnosticProfile interface for all versions starting from win7 up to win11? Does it changes between versions?

**Comment by hfiref0x** [comment]
I will add this method in the next version, but this could take some time as I don't have any free time for this now. Thanks for your contribution.

You can check the interface layout using IDA, this interface is in diagcpl dll I believe.

**Comment by hfiref0x** [comment]
This is method 75. It is not a final version and mainly untested. You need properly compiled dlls for akagi to be able to test this method, follow instruction in readme.md, without properly integrated dll this method won't work.

**Comment by hfiref0x** [comment]
Implemented in b0855e23627524005d539e37a9a65abb4d9d1865

**Comment by sly9it** [comment]
> It presents starting from Windows 7 and the latest version I got is Win10 build 19041 which is also having it.

How did you get this compiled in windows 10
