### ISSUE TITLE
Few questions about PEB data

### ISSUE THREAD

**Issue by slientbone** [hfiref0x/UACME#135]
Hello hfiref0x,

Just created this account to say thanks for your project, love your work. I have question, though, when spoofing PEB loader data, why is it necessary to change the command line of the process? It seems base file name is enough. Also, do you know symbol name in appinfo.dll where PEB data of RPC client is checked?

Thanks.

ps. unrelated but your opinion on better system for x86/x64 reverse-engineering/low-level/systems programing: windows or linux? I currently use windows but since you seem pro in this I would like to know your thoughts on this.

pps. your twitter seems gone. made a new account??

**Comment by hfiref0x** [comment]
Hello,

imagepath should be enough. Command line, well it's an artefact from the past when this code was created where UAC bypass wasn't the main goal of it. If it works - then remove this artefact. I don't remember where exactly this is checked but Windows use only peb loader data. 

Start from Windows, it's easiest way - tons of stuff, software, tutorials etc that actually _works_. As of Linux - it software ecosystem can kill all your interest and motivation if you just beginning to do something without any base. If you feel yourself enough motivated and ready to dig into ~open source trash~ software - you are welcome.

Twitter account deleted as I don't see any point in my further presence in this social network.

**Comment by slientbone** [comment]
Got it, thanks for the advice.
