### ISSUE TITLE
How is icolordataproxyvtbl structure generated?

### ISSUE THREAD

**Issue by secxue** [hfiref0x/UACME#136]
Hi bro, how is icolordataproxyvtbl structure generated?

![image](https://user-images.githubusercontent.com/89639483/188538530-1c23099b-27d4-4d7e-81fa-0c9aa1b23a1d.png)

I use OleViewDotNet, but the result is different from yours
![image](https://user-images.githubusercontent.com/89639483/188538664-f4b619dc-0bf1-464d-8e53-dcee03a4bbef.png)

**Comment by hfiref0x** [comment]
With ida pro

**Comment by secxue** [comment]
Thanks for you reply.
Hava have any articles on this?
I want to learn

**Comment by secxue** [comment]
> With ida pro

Thanks for you reply.
Hava any articles on this?
I want to learn

**Comment by secxue** [comment]
> With ida pro

Thanks for you reply.
Hava any articles on this?
I want to learn "just use ida pro to find these structures"

**Comment by secxue** [comment]
> With ida pro

What I want to ask is how to do this through ida pro, plugin?
Is it the original function of IDA

**Comment by hfiref0x** [comment]
Open designated dll in the IDA Pro.

**Comment by secxue** [comment]
> 在 IDA Pro 中打开指定的 dll。

After open dll in ida pro, is it generated manually or can it be automated then struct?
Do want to construct manually?

**Comment by hfiref0x** [comment]
Load file into disassembler, enable symbols otherwise this won't work. Find a corresponding class by name in functions view, look where it vtable located. Done. Specific parameter names maybe not listed in symbols and you have to figure out what they do by analyzing method body.

**Comment by secxue** [comment]
> 将文件加载到反汇编程序中，启用符号，否则这将不起作用。在函数视图中按名称查找相应的类，查看它的 vtable 所在的位置。完毕。具体的参数名称可能没有在符号中列出，您必须通过分析方法体来弄清楚它们的作用。

Thanks for you reply.
At first, I thought it could be done automatically :)

**Comment by secxue** [comment]
> > 将反加载函数视图显示到，而不是这个程序中将显示的参数。出来的方法，必须通过您的分析体来的作用。
> 
> 谢谢你的回复。 起初，我认为它可以自动完成:)

Now I know that it is my imagination that does evil.
