### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by St0rn** [hfiref0x/UACME#14]
Hi,
Your tool is great then which source represents the method 30?
Thanks a lot by advance.

**Comment by hfiref0x** [comment]
List of methods id's 
https://github.com/hfiref0x/UACME/blob/master/Source/Akagi/methods/methods.h#L23

Table of methods
https://github.com/hfiref0x/UACME/blob/53652612c59337a7c09990f1f73572bbdbe53c2f/Source/Akagi/methods/methods.c#L47

30 is UacMethodWow64Logger and method is MethodWow64Logger

**Comment by St0rn** [comment]
Thanks
