### ISSUE TITLE
UAC-ME Method 77 not working.

### ISSUE THREAD

**Issue by payloads45** [hfiref0x/UACME#142]
Hi hfiref0x,

Thanks for the tool, I tried to emulate Method 77 by **Arush Agarampur** , I am attaching the screenshot along with this, please help me with it. 

![image](https://user-images.githubusercontent.com/111106697/218641518-77d82bb3-a38e-4476-892a-9342ded26857.png)

Thank you!

**Comment by hfiref0x** [comment]
Hello,

how did you compiled this executable?

**Comment by payloads45** [comment]
Hi,

I just used the very recent VS Solution file, and built it with `Build Solution`  . Thanks!

**Comment by hfiref0x** [comment]
You didn't followed build instructions. Your result executable is invalid.
