### ISSUE TITLE
63,65-68 may have been fixed?

### ISSUE THREAD

**Issue by Mosney** [hfiref0x/UACME#145]
```
Windows 11 Pro
22H2 22621.1848
```

I just try every method still cotained in 3.6.4, found some methods look unwork as expected(pop up a CMD window).

63. uac request by `msschedexe.exe` then a terminal-liked windows titled `C:\WINDOWS\system32\SecureBootEncodeUEFI.exe` flash in&out, but no administrator CMD show.

65,66,67,68 have no request at all, Maybe they've been fixed?

**Comment by hfiref0x** [comment]
65-68 are protocol hijacks, more possible that code responsible for UserAssocSet is not compatible with win11 changes since this code wasn't updated from nov 2021.

**Comment by hfiref0x** [comment]
I have:

1) installed this pack of crap -> 22621.1848.230608-1957.NI_RELEASE_SVC_PROD1_CLIENTMULTI_X64FRE_EN-US.ISO;
2) updated shell32.dll signature scan for **UserAssocSet** for 22621 (as signature was indeed incompatible with this OS version); 
3) removed WinDefend to avoid system heavy load and possible interactions through it schizophrenic behavior rules;
4) run 63, 65, 66, 67, 68, screenshots below.
![63](https://github.com/hfiref0x/UACME/assets/10708977/e0ccca31-87a6-4ebb-a0ac-bc2ac7292586)
![65](https://github.com/hfiref0x/UACME/assets/10708977/10450e92-615c-40ee-ad9a-fed6393c6d0d)
![66](https://github.com/hfiref0x/UACME/assets/10708977/16f87d57-3d2b-4f26-87a4-b25c8edb520a)
![67](https://github.com/hfiref0x/UACME/assets/10708977/24f8281f-3489-461a-9921-a5b72de7a45f)
![68](https://github.com/hfiref0x/UACME/assets/10708977/21644876-9117-4ee6-b38f-e685899c7d55)

As you see conceptually nothing changed, all of them works perfectly.

The reason why 63 maybe failing for you is that it is very resource consuming as it involves cleaning native image cache which may trigger multiple other things we can't predict.
