### ISSUE TITLE
ERR C1085 Cannot open include file: 'fusion.h': No such file or directory	

### ISSUE THREAD

**Issue by blackdarksy** [hfiref0x/UACME#151]
can help plz , get ERR when build
using Visual Studio 2022
Severity Code Description Project File Line Suppression State Details
Error C1083 Cannot open include file: 'fusion.h': No such file or directory	Akagi C:\Users\server\Downloads\UACME-3.6.4\Source\Akagi\global.h	69		

![image](https://github.com/hfiref0x/UACME/assets/154058057/1c27c312-a110-4078-8452-0e316f71ec40)

![image](https://github.com/hfiref0x/UACME/assets/154058057/cec0385f-0e47-4bbf-8954-4db6ba86040e)

**Comment by hfiref0x** [comment]
https://github.com/hfiref0x/UACME/issues/126
