### ISSUE TITLE
Successful build... But at what cost?

### ISSUE THREAD

**Issue by ASDF123214321** [hfiref0x/UACME#152]
decided to put something as the title.

As the title suggests, The binary came out with all the icons and everything, but executing it with the correct params/no params returned nothing.
`
C:\Users\win10\source\repos\UACME\Source\Akagi\output\x64\Release>Akagi64.exe

C:\Users\win10\source\repos\UACME\Source\Akagi\output\x64\Release>`
`
C:\Users\win10\source\repos\UACME\Source\Akagi\output\x64\Release>Akagi64.exe 1 C:\Windows\System32\cmd.exe

C:\Users\win10\source\repos\UACME\Source\Akagi\output\x64\Release>`

Can someone help?
Windows SDK ver: 10.0.20348.0
Visual Studio ver: Community 2022
(windows defender protection off)

**Comment by hfiref0x** [comment]
Method 1 obsolete and not present in 3.6.6 version as I assume you compiled it. This is clearly stated in the readme file under "Keys" section.

**Comment by ASDF123214321** [comment]
I tried it under other keys, but still did not output anything.

**Comment by hfiref0x** [comment]
How did you build it?

**Comment by ASDF123214321** [comment]
Started with debugger, failed build so I read the README, placed all binaries in the root bin dir, and ran Naka64 on all of the DLLs and EXEs. I then compiled Akagi by right clicking on the project and clicking Build.

**Comment by hfiref0x** [comment]
Did you generated secrets blob for your binaries in bin folder?

**Comment by ASDF123214321** [comment]
I ran Naka64 in the repo root's bin folder, which put everything (including secrets) inside it.

**Comment by hfiref0x** [comment]
When you run naka over dll files it generates AES encrypted binaries, with CD extension. Next you need to build secrets blob by running "naka64 --stable" (without quotes). If everything is done properly result will be secrets32/secrets64.bin files. After this you should rebuild akagi.exe in Release configuration.

**Comment by ASDF123214321** [comment]
I'll try it when I can.

**Comment by ASDF123214321** [comment]
@hfiref0x Just tried what you told me to do. .CD files generate, but running "naka64 --release" did nothing to the directory. The "Akagi" dir in Source has a folder called "bin". It has all the files needed, but they are all 0 bytes in size.

**Comment by hfiref0x** [comment]
You didn't compiled what is required for this operation.

**Comment by rafa-br34** [comment]
So it turns out you also need the 32-bit version for Fubuki as seen [here](https://github.com/hfiref0x/UACME/blob/master/Source/Naka/main.c#L1115).

**Comment by hfiref0x** [comment]
@rafa-br34 
Yes, some methods rely on dropping 32 bit dll into syswow64 folder AFAIR, thats why 64bit akagi have both 32/64 bit fubuki.
