### ISSUE TITLE
fusion.h no such file or directory

### ISSUE THREAD

**Issue by Mostafa-hazem** [hfiref0x/UACME#154]
I am trying to compile akagi (uacme.sln) project using visual studio 2022(v143) and SDK 10.0.22.621.0 after building solution an error shows "1>UACME-master\Source\Akagi\global.h(74,10): error C1083: Cannot open include file: 'fusion.h': No such file or directory"
any suggestion/

**Comment by hfiref0x** [comment]
https://github.com/hfiref0x/UACME/issues/126
