### ISSUE TITLE
Windows Vista - Akagi.exe is not a valid Win32 application

### ISSUE THREAD

**Issue by AsuraBit** [hfiref0x/UACME#17]
Hi, I tested UACME on windows XP-7-8-8.1-10, and it works on everyone except on Vista, tested with 32 bit and 64 bit.
Both show me this error:
Akagi32.exe is not a valid Win32 application
or
Akagi64.exe is not a valid Win32 application

Thanks

**Comment by hfiref0x** [comment]
System Requirements

x86-32/x64 Windows 7/8/8.1/10TH1/10TH2/10RS1/10RS2 (client, some methods however works on server version too).
