### ISSUE TITLE
About DismMethod

### ISSUE THREAD

**Issue by givemepoison** [hfiref0x/UACME#19]
Hi, I can not understand the procedure for the DismMethod. I see:

1) Drop dismcore.dll in system32 using iFileOperation
2) Drop .xml file in %temp%
3) Start PkgMgr.exe with parameter /n:%temp%\file.xml
4) ??? 
5) My program is started with admin rights

What happens in step 4 and where is the path to my program indicated? Thank you.

**Comment by hfiref0x** [comment]
In your fake dismcore.dll
What happens I posted here -> http://www.kernelmode.info/forum/viewtopic.php?p=28872#p28872

**Comment by givemepoison** [comment]
Where can I get the sources of dismcore.dll?

**Comment by hfiref0x** [comment]
From the same place where you got the rest.
