### ISSUE TITLE
Use in PowerSploit

### ISSUE THREAD

**Issue by redfast00** [hfiref0x/UACME#2]
Hi, I really like your project, can I convert your code so it works in PowerShell? I would like to put it in PowerSploit (https://github.com/mattifestation/PowerSploit), and/or in Empire (https://github.com/PowerShellEmpire/Empire)

Thanks, redfast00

**Comment by hfiref0x** [comment]
Hello, yes you can.

**Comment by redfast00** [comment]
Implemented, but they refused to add it to the main repo
