### ISSUE TITLE
Used on Main Computer #2

### ISSUE THREAD

**Issue by FuatCemOzyazici** [hfiref0x/UACME#22]
I have tried method 35 which was about token manipulation and it was successful to elevate. However, some exe files in my computer are not working properly anymore. Example: sdiagnhost.exe. How can I solve this? I think it is about registry. Please help me. Thank you.

**Comment by FuatCemOzyazici** [comment]
By not properly, i mean they are opening as CMD window

**Comment by hfiref0x** [comment]
It wasn't 35 method. It was some of methods related to HKCU\\Software\\Classes\\exefile\\shell\\runas\\command runas changes.

**Comment by FuatCemOzyazici** [comment]
Probably it happened when i tried other options, how can I restore it? Can you tell me the original values of this key? Thank you :)

**Comment by hfiref0x** [comment]
find references to "c:\windows\system32\cmd.exe" here and del it

**Comment by FuatCemOzyazici** [comment]
There are no references for it. Please guide me. Only some exes are opened as cmd.

**Comment by hfiref0x** [comment]
Details about your system. Full version. What exes? I'm not a telepath.

**Comment by FuatCemOzyazici** [comment]
sdiagnhost.exe runs automatically on random times as CMD window.
I have downloaded a new program called CyberGhost VPN and it also opened as CMD window as well. What should I do to reverse this?

**Comment by FuatCemOzyazici** [comment]
Windows 10 64 bit 15063

**Comment by hfiref0x** [comment]
Del these artifacts if they exist
https://github.com/hfiref0x/UACME/issues/9#issuecomment-267741576

Clean your %temp% folder.

**Comment by FuatCemOzyazici** [comment]
Problem still exists.

**Comment by hfiref0x** [comment]
Run your problem application with procmon and show log.
