### ISSUE TITLE
Opens cmd now every time I open Visual Studio or something made in Visual Studio

### ISSUE THREAD

**Issue by 1075** [hfiref0x/UACME#23]
I ran one of the parameters with UACMe (one of the 30s, I think). Since then, every time I run Visual Studio or a program I made in Visual Studio I get a window of cmd and also this message
![default](https://user-images.githubusercontent.com/8387003/32995097-8d91f02a-cd78-11e7-96bf-cab144a3c65b.png)
After I close the message, the program closes.
Weird.
I hope you can help!

**Comment by hfiref0x** [comment]
https://github.com/hfiref0x/UACME/issues/22

**Comment by 1075** [comment]
I found one .dll with UACMe in the description, and deleted it.
The rest were all by Windows, and required TrustedInstaller to delete. I assumed that meant that UACMe didn't switch those for its own, and just left them there.
In addition, I cleared C:\Windows\TEMP.
CMD still opens when I open Visual Studio or anything I make in it, along with that message. Still, when click OK, the program closes. 
By the way, the Visual Studio splash screen does open, it just closes when I click OK.
I checked the exefiles registry keys too for C:\Windows\System32\cmd.exe. There was nothing there.
Can you please guide me as to how to use ProcMon and upload the log? Or do you have any other solutions? Is this a known problem, i.e.: Did UACMe make that message appear, or is it something that Windows made? 
Thanks a bunch!

**Comment by hfiref0x** [comment]
%temp% is your local temp folder, usually C:\\Users\\UserName\\AppData\\Local\\Temp
This message is from uacme dll, it is not a known problem, do not run it on real machine unless you don't know how it work.

Check these keys:
HKEY_CURRENT_USER\\Software\\Classes\\exefile\\shell\\runas\\command, the default value should be empty, if IsolatedCommand value also present it should be "%1" %*

HKEY_CURRENT_USER\\Software\\Classes\\mscfile\\shell\\open\\command, the default value should be mmc.exe "%1"

HKEY_CURRENT_USER\\Software\\Classes\\CLSID\\{0A29FF9E-7F9C-4437-8B11-F424491E3931}\\InProcServer32, this regkey should not exist

... or if it doesn't help

When message displayed, run process explorer and select devenv.exe, enable Dlls panel view for this process. Find here uacme dll by description field.

... or if it doesn't help

Setup procmon log filter "Process Name", set it to your problem process (devenv.exe). Procmon capture settings: Show File System Activity -> On, Show Registry Activity -> On, Network&Process off. Then run devenv.exe elevated as on your screenshot.

**Comment by 1075** [comment]
Got it! It was disguised as MSCOREE.DLL. That explains why it opened only in Visual Studio (built in .NET which uses MSCOREE.DLL), and anything I made in it (I use VB.NET, again using MSCOREE.DLL)!
Thanks a ton!

**Comment by FuatCemOzyazici** [comment]
@hfiref0x 
https://files.fm/u/6zzmmbb7

Here is sample log file.

**Comment by FuatCemOzyazici** [comment]
Please help me. I can't run several programs. They always open as CMD window.

**Comment by hfiref0x** [comment]
Goto C:\Windows\Microsoft.NET\Framework64\v4.0.30319\

and delete MSCOREE.DLL (this is fubuki dll, verify it in file properties).

**Comment by FuatCemOzyazici** [comment]
Thank you problem solved !! :)
