### ISSUE TITLE
Could you compile method 42 separately ?

### ISSUE THREAD

**Issue by bobsadino** [hfiref0x/UACME#25]
Please help me to compile method number 42

i dont know how to compile because its hard to understand

do you have method 42 source code standalone?
 
It's so hard to understand the code once they are mixed.
and we should categorize. like Unfixed till now and what OS
Big Thanks.

**Comment by bobsadino** [comment]
i dont understand all of this https://github.com/hfiref0x/UACME/blob/master/Source/Akagi/methods/fwcpllua.h

**Comment by hfiref0x** [comment]
No.

**Comment by bobsadino** [comment]
so stingy why?

**Comment by hfiref0x** [comment]
Your profile can be found on hackforums.net where you ask the same question. Your profile links to twitter account twitter.com/bobsakino, which itself link to "portfollio" hxxps://iluvbbw.000webhostapp.com/. Looking on it, it suggests that you are malware developer. 
Developing malware is illegal and will lead to legal consequences. I do not create malware, I do not help malware authors in any form. All the above data saved and will be used against you in case of a request from the law enforcement services. This conversation is over.
