### ISSUE TITLE
How to escape the double quotation marks in command line parameters?

### ISSUE THREAD

**Issue by gmxyb** [hfiref0x/UACME#26]
For example a command line like this:

"C:\Program Files\xxx\yyy.exe" "d:\path include space\my.data"

Akagi64.exe 35 ?????

**Comment by hfiref0x** [comment]
I don't remember when this "Issues" section turned into forum for general C/Windows programming. Seriosly, what do you _expect_ asking this unrelated question here? Answer? Answer is - this is not related to UACMe project issues, closed.
