### ISSUE TITLE
Method 45 (ucmMethodSluiHijack) has been patched

### ISSUE THREAD

**Issue by EinderJam** [hfiref0x/UACME#27]
Since Windows 10 v1803, the ucmMethodSluiHijack has been patched. Upon execution,it opens Windows settings with a dialog box prompting for a Windows Key.

**Comment by hfiref0x** [comment]
![1](https://user-images.githubusercontent.com/10708977/40635188-01867ca4-6323-11e8-8bd5-adf8fe07f427.png)

**Comment by LimiQS** [comment]
Insider 17692. Repro success
![image](https://user-images.githubusercontent.com/9378097/42460624-f233b216-83d0-11e8-8909-747ca67f159b.png)

**Comment by hfiref0x** [comment]
![12](https://user-images.githubusercontent.com/10708977/42460963-808a8ef2-83c9-11e8-96df-85ffd0708f72.png)

Not reproducable.
