### ISSUE TITLE
Missing 32 bit version

### ISSUE THREAD

**Issue by Kaicastledine** [hfiref0x/UACME#30]
Hello,

Seems the 32 Bit version has been removed from the bin folder ?

Kind Regards

**Comment by hfiref0x** [comment]
https://github.com/hfiref0x/UACME/commit/9c22c333792644cfd8c455f8dcdd4931d1d9d188

"Compiled binaries removed due to continues abuse from sk trash and scamware projects (thor, uacguard etc)".
