### ISSUE TITLE
Some files & keys may left after POCs (23, 36, 37, 43) run.

### ISSUE THREAD

**Issue by LimiQS** [hfiref0x/UACME#31]
(23). [file] `%systemroot%\System32\dismcore.dll`
(36). [multiple files] MSCOREE.dll (in various paths recorded in `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\KnownFunctionTableDlls`, e.g. `C:\Windows\Microsoft.NET\Framework64\v2.0.50727\`)
(37). [folder] `%systemroot%\System32\dccw.exe.local`
(43). [registry] `HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ICM\Calibration\DisplayCalibrator`
I'm not sure if (36) and (37) left residual file by mistaken or intended or some thing incorrect with my PC configure, but the other two did not implement cleanup.
PS. Residual file left by (36) may cause any .NET program cannot start properly after system restart.
Environment: Build 17692

**Comment by hfiref0x** [comment]
Removal of files/keys in some of methods should be done by user. This program is not intended to be run on real machine.

**Comment by hfiref0x** [comment]
https://github.com/hfiref0x/UACME/commit/c43f344f78ea5db67d9c3be587da52ff5da228f7 commit should resolve this. This wasn't possible before 3.0.x because of dlls/uacme limitations.
