### ISSUE TITLE
Method 45 failed. May caused by accessed registry path changed.

### ISSUE THREAD

**Issue by LimiQS** [hfiref0x/UACME#32]
Quoted from bytecode77/slui-file-handler-hijack-privilege-escalation:
> Read access to HKCU\Software\Classes\exefile\shell\open is performed upon execution. Due to the registry key being accessible from user mode, an arbitrary executable file can be injected.

But in the actual test, the registry key slui.exe accessed is `HKCR\exefile\shell\open\command` not the one mentioned by bytecode77. After changing the value of the HKCR one to cmd.exe, cmd window (Medium IL) shown after slui.exe is executed.

![image](https://user-images.githubusercontent.com/9378097/42487514-f2fcc01c-8433-11e8-9a68-fd79a495d12d.png)

Environment:
![image](https://user-images.githubusercontent.com/9378097/42487845-746f8750-8435-11e8-8f6c-687d4a20d739.png)

**Comment by hfiref0x** [comment]
Windows 10 17711 clean install, nothing else installed, no registry changes, clean snapshot. Logs clearly indicate that after searching for exefile handler shell goes to HKCU. Nothing changed here, except WD behavior signature from MS targetting several registry keys.

Your fail is not reproducable. Successful UAC bypass. Unless I won't be able to 100% reproduce it here - I won't do anything or set "fixed" to that method.

![w10](https://user-images.githubusercontent.com/10708977/42488425-aab5b45c-842f-11e8-8e85-02c189165746.png)
