### ISSUE TITLE
Build on VS 2015

### ISSUE THREAD

**Issue by GGGunrunner** [hfiref0x/UACME#38]
I've got a fresh install of Win 8.1 and VS 2015 in Virtualbox.

When opening the solution, it says:

The build tools for v141 cannot be found. Install v141 to build using the v141 build tools."

Went to Project - Properties - but there is no "General" submenu at all.
Only "Common Properties" and "Configuration Properties", thats it. So I cant choose anything related to build tools...

Anyone there to help? Thanks!

**Comment by hfiref0x** [comment]
You didn't selected actual "Project" to view properties of. Instead you are viewing "Solution" properties.

**Comment by GGGunrunner** [comment]
Upper manu bar
File | Edit | View | Project | Build | Debug | Team .. etc etc
selected this       ^^^^^^^^^
then Properties..

or is there another way? thanks!

**Comment by hfiref0x** [comment]
View -> Solution Explorer. In it select project you want to build then go to it properties.

**Comment by hfiref0x** [comment]
¯\_(ツ)_/¯
