### ISSUE TITLE
VCRUNTIME140D.dll not found

### ISSUE THREAD

**Issue by GGGunrunner** [hfiref0x/UACME#39]
Managed to build Akagi in Virtualbox - Win 7 + VS 2017. No errors

But when I'm launching it in the same barebone Win 7 (mid-2015, no updates) environment,
it throws an error about VCruntime dll.... Can I change the build options or statically link or something? In the realworld scenario, with many Win7, Win 8.1, Win 10, not all of them would have VCR dll either, right?

**Comment by MartinDrab** [comment]
Hello,

yes, you need to set the runtime library to static link (**Multi-threaded** or **Multi-threaded Debug** values of the Run-time library option in the project properties -> C/C++ -> Code Generation].

Normally, you can solve this problem asl oby shipping necessary DLLs with your application, however, I would not go this way in this case.

**Comment by GGGunrunner** [comment]
Great, thanks a lot! :)

**Comment by hfiref0x** [comment]
You are building in the Debug. To build without runtime dependencies you should build in "Release".
