### ISSUE TITLE
stdout instead of messagebox

### ISSUE THREAD

**Issue by shiad** [hfiref0x/UACME#44]
Hello,
1.How can i switch result messages to cmd stdout? instead of messageboxes. For example wanna to write:
`Usage: Akagi.exe [Method] [OptionalParamToExecute]`
on cmd stdout. In otherword, i want to switch it from UI to command-line interface.
2.How can i use compiled Dll?

Thanks again to your great repo!

**Comment by hfiref0x** [comment]
1. Set Console subsystem in linker and use https://docs.microsoft.com/en-us/windows/console/writeconsole.
2. Load library, get proc address of procedure by ordinal 1927, execute it - see ucmRunMethod for parameters info.

**Comment by shiad** [comment]
Solved, Thanks!
