### ISSUE TITLE
how to use with metasploit?

### ISSUE THREAD

**Issue by CyberTheReape** [hfiref0x/UACME#46]
hello. Thanks for this project. but i dont understand. How can we use uacme with metasploit ? Once you have uploaded the uacme file to the target computer, how can we use it?

**Comment by hfiref0x** [comment]
All third-party software and integration with it is not my bussiness.

**Comment by CyberTheReape** [comment]
Why you dont have wiki document?

if you have a wiki document, I could do the integration process myself.

I couldn't find a website about how to use uacme..

Can you show me a website that explains exactly how to use this program?
