### ISSUE TITLE
55

### ISSUE THREAD

**Issue by moaeddy** [hfiref0x/UACME#47]
method 55 not in UACME build, tried on win10 x64 still request parameter input while its correct

**Comment by hfiref0x** [comment]
![untitled](https://user-images.githubusercontent.com/10708977/53019237-e2fcef80-3486-11e9-9292-3002303252f3.png)

No it is. You either not recompiled current version or doing something wrong.

**Comment by moaeddy** [comment]
ok, just gonna run akagi64 55 with no file to run as administrator e.g CMD?

**Comment by hfiref0x** [comment]
It works the same as others. There is no difference.

**Comment by hfiref0x** [comment]
The other implication why it may be not working for you - a foreground window different than msconfig.exe or cmd.exe is intercepting input. Anyway I cannot confirm your initial report.
