### ISSUE TITLE
Method 36: DLL Hijacking Left Overs

### ISSUE THREAD

**Issue by repnz** [hfiref0x/UACME#49]
Hey:)
- Using method 36 the DLLs used for hijacking (in the .NET directory) are not cleaned, Thus every .NET executable that is opened after running this method is replaced with an instance of cmd.exe.
- The DLLs can be MSCOREE.dll or OLE32.dll.
- I would have fixed this issue myself but Akagi cannot remove the DLL because it needs to be elevated (lol), I thought the correct way to fix this is using the payload DLL to remove itself somehow. What do you think?

**Comment by hfiref0x** [comment]
You can try use elevated IFileOperation:DeleteItem from akagi. However there is no ready to use code in akagi to do so. This code will be not really different from https://github.com/hfiref0x/UACME/blob/master/Source/Akagi/methods/comsup.c.  Also if these dlls are mapped into running process(es) this will eventually fail.

**Comment by hfiref0x** [comment]
Should be fixed in https://github.com/hfiref0x/UACME/commit/c43f344f78ea5db67d9c3be587da52ff5da228f7. However I still unadvise to use this program on real PC's.
