### ISSUE TITLE
Compile errors on Win 10 64 17134.648/VS 2015

### ISSUE THREAD

**Issue by kenny1983** [hfiref0x/UACME#52]
Hi,

I'm trying to compile the latest Akagi project on Windows 10 64 bit Build 17134.648 using Visual Studio 2015 14.0.25123.00 Update 2. I get 174 compile errors that all seemingly stem from a single line of code in shared/ntos.h: line 9071 where VS complains that "identifier PMEM_EXTENDED_PARAMETER is undefined".

By Googling that type name I found https://docs.microsoft.com/en-us/windows/desktop/api/winnt/ns-winnt-mem_extended_parameter which says that the type should be defined in winnt.h. If past experience serves me correctly, this header should never be included directly; rather windows.h should be included instead (I don't understand how this works since windows.h doesn't include winnt.h directly, but it has always worked for me in the past). This is done in the project's global.h. So what gives??

I've followed the build instructions to the letter (set "Platform Toolset" to v140 and "Target Platform Version" to 8.1 in project properties) but since that aforementioned MS docs page says that Windows 10 is required, I'm guessing that the latter option should be set to 10.0.17134 as suggested for VS 2017, and that the appropriate SDK is required. I'm downloading the SDK as we speak to test this, but thought I'd create an issue here in the meantime, to alert others of the issue if nothing else.

Anyway going back to the instructions for VS 2015, I have the 8.1 SDK installed at C:\Program Files (x86)\Windows Kits\8.1 and the include directories are all setup properly in VS (I am sure of this as other projects targeting the same SDK work fine). The external dependencies (all 216 of them!) show up fine under that node of the solution explorer, yet I'm still having this incredibly-infuriating problem!

As a quick aside, I always seem to have this kind of problem when compiling a large GitHub-hosted project myself, and as such I wish there would be precompiled binaries provided in the repo AS WELL AS the source code. It makes life infinitely-easier for people like me who always seem to be missing one or two crucial system headers.

MTIA to anyone who can shine some light on this! :-)

**Comment by hfiref0x** [comment]
It is parameter of NtCreateSectionEx. The whole definition was taken from ProcessHacker and this wasn't tested with old < 10 SDK. Obviously since this is Windows 10 function the required prototype is missing in 8.1 SDK. To fix this error correct this function definition and set this parameter to PVOID instread of PMEM_EXTENDED_PARAMETER. This will be fixed in todays update anyway.

**Comment by kenny1983** [comment]
Ahh OK that makes sense! I thought it was due to the old SDK; thanks mate I will apply your suggested fix :D

Also many thanks for your ongoing effort on this project and for the super-fast reply! Peace B-)

**Comment by hfiref0x** [comment]
As of precompiled binaries the reason(s) why they are removed:
1) They are used by various untrustworthy people and sometimes requirement to build them from source is perfect blocking barrier for their skills
2) They are detected as malware by various AV's including Microsoft
3) Microsoft owns this platform and don't rely want provoke them

Here is the example what can happen when precompiled binaries included and they are considered as malware -> https://github.com/LordNoteworthy/al-khaser (Google Safe browsing mark this page as malicious, while it obviously not).

**Comment by kenny1983** [comment]
Ahh fair enough, yeah that makes perfect sense and I apologise if my comment seemed nasty. Windows Defender wouldn't even let me download the repo zip for the same reason; had to temporarily disable it to get around that! Anyway thanks again! :D
