### ISSUE TITLE
sxsFilePathNoSlash and sxsFindLoaderEntry double-defined in util/sup.c

### ISSUE THREAD

**Issue by kenny1983** [hfiref0x/UACME#53]
Hi,

It seems as though the functions sxsFilePathNoSlash and sxsFindLoaderEntry are defined in both util.c and sup.c. Commenting them out in one file or the other solves the problem, but I was just wondering whether both files are really necessary? If so, which one should have its defs of sxsFilePathNoSlash and sxsFindLoaderEntry removed?

MTIA! :-)

**Comment by hfiref0x** [comment]
util.c used only by dlls, sup.c used by Akagi only.

**Comment by kenny1983** [comment]
Great, thanks for the info!
