### ISSUE TITLE
UAC bypass with Direct call to RAiLaunchAdminProcess and mmc

### ISSUE THREAD

**Issue by CaledoniaProject** [hfiref0x/UACME#55]
References: https://github.com/DimopoulosElias/alpc-mmc-uac-bypass

**Comment by hfiref0x** [comment]
This is mediocre copy-paste work from guy who doesn't know what he copy-pastes.

This method implemented in uacme as 38 (ucmHakrilMethod), implemented like soon 2 years ago (https://github.com/hfiref0x/UACME/commit/f6017a531ad64d164b87eb232e2550ae84c9de08).

This guy took Forshaw code from https://bugs.chromium.org/p/project-zero/issues/detail?id=220 for calling Rpc interface, this one from HexRays output (without even refactoring it and removing auto generated HexRays variables) and... that is all the difference. Oh, and mentioned "private" keyword for hype on twitter.

**Comment by CaledoniaProject** [comment]
Sigh, let's just close this issue.
