### ISSUE TITLE
Elevation checking

### ISSUE THREAD

**Issue by Hackernese** [hfiref0x/UACME#60]
Question, is there anyhow i can check whether UACme has successfully elevated or not ? like return code or something ? so far as i see, return code always returns 0 no matter if it fails or succeeds

**Comment by hfiref0x** [comment]
Which one method?

**Comment by Hackernese** [comment]
Oh... For instance, Method 4, 46, don't seem to work anymore on Windows 7

**Comment by Hackernese** [comment]
architecture : AMD46, 
( 64 bit )

**Comment by hfiref0x** [comment]
Method 4 is only x86. After MS released Windows 7 SP1 rollup update sdbinst.exe updated it manifest and this method have been fixed completely.

**Comment by Hackernese** [comment]
Oh, well... thnk anyway, i can still use the others :P
But isn't there like a return code in %errorlevel% or something to check whehter things have been elevated successfully ?

**Comment by hfiref0x** [comment]
Exe sets process exit code to result value. It is STATUS_SUCCESS on success (all preparations succeded and elevation requested, however elevation is not guaranteed) or any other value that mean error.

**Comment by Hackernese** [comment]
so methods 4 and 46 will return something isn't STATUS_SUCCESS ?
( Also, what is STATUS_SUCCESS you mean, an environment variables ? )

**Comment by hfiref0x** [comment]
https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-getexitcodeprocess
