### ISSUE TITLE
Im New! Help?

### ISSUE THREAD

**Issue by FlappyDude2003** [hfiref0x/UACME#66]
Hey, im new to all of this stuff, is there a bypass working for windows 10 right now? if so what do i compile and how do i compile it?

**Comment by hfiref0x** [comment]
They all listed in readme.md as "unfixed"
Install Visual Studio, Windows 10 SDK.

**Comment by FlappyDude2003** [comment]
But wait, what .c file do i compile? im sorry.

**Comment by lupier** [comment]
>  im sorry.
It looks like your level of knowledge is still pretty low for this repository. This is not a "noobie" place . Learn by yourself at 1st step, good luck

**Comment by FlappyDude2003** [comment]
ha, i found i need to compile the solution, but i cant find cl.exe because
i havent installed desktop development. i think im learning.
