### ISSUE TITLE
How to modify the code under Fubuki folder?

### ISSUE THREAD

**Issue by cuipi254645734** [hfiref0x/UACME#67]
How to modify the code under Fubuki folder?
I tried to modify the code in the dllmain.c of the Fubuki folder, but after compiling successfully, nothing changed in execution. 
I use OutputDebugString in the DllMain function in dllmain.c， and use DebugView to view it without any output.
Could you please help to answer it? Thank you very much！！

**Comment by hfiref0x** [comment]
https://github.com/hfiref0x/UACME/issues/43
