### ISSUE TITLE
How do I use OutputDebugString to print variables of type PUCHAR

### ISSUE THREAD

**Issue by cuipi254645734** [hfiref0x/UACME#69]
how to use OutputDebugString to print UncompressedData of type PUCHAR in the DecompressPayload function.
I tried OutputDebugString(UncompressedData), but the print was garbled.
Can you help me?

**Comment by hfiref0x** [comment]
Why do you need this. If you want to look at contents of this buffer you can do that from Visual Studio -> Debug - > Memory window.

**Comment by cuipi254645734** [comment]
Thanks. I'll try.
