### ISSUE TITLE
 Method 58 and the "User Account Control" popup

### ISSUE THREAD

**Issue by ACPMMD** [hfiref0x/UACME#70]
Hello,
I implemented the 58th method based on your code.
I found that when the program executes to CoGetObject, 
the windows system would pop up with a "User Account Control" popup. 
May I ask what might cause this?
When I click “yes”, the program pops clipup.exe.
I want to ask if I missed any function that didn't implement?

**Comment by hfiref0x** [comment]
Did you patched PEB?

**Comment by cuipi254645734** [comment]
"G_hInstance = (HINSTANCE) NtCurrentPeb () - > ImageBaseAddress;" in my code. 
The structure definition of PEB is also included in the ntos.h file.
What does patched PEB mean? Can you be more specific?

**Comment by hfiref0x** [comment]
Look at supMasqueradeProcess

**Comment by cuipi254645734** [comment]
Got it. Thank you!!

**Comment by ACPMMD** [comment]
Theoretically, regarding method 58, could I directly pass Fubuki.dll into the ucmEditionUpgradeManagerMethod function and do not consider the process of encryption and decryption ?

**Comment by hfiref0x** [comment]
https://gist.github.com/hfiref0x/de9c83966623236f5ebf8d9ae2407611

**Comment by ACPMMD** [comment]
I can't open this URL.

**Comment by ACPMMD** [comment]
URL is open, thanks!!

**Comment by ACPMMD** [comment]
What is loader.exe in akagi_58a.c? How to get it?

**Comment by hfiref0x** [comment]
It is your payload.

**Comment by ACPMMD** [comment]
How should the payload be made?I tried to replace loader.exe with Fubuki64.dll, but the program did not execute successfully.

**Comment by hfiref0x** [comment]
This question is out of scope of this issue section.

**Comment by ACPMMD** [comment]
I understood what you meant later. Thank you！
