### ISSUE TITLE
I  would like to stop Passing arguments into Akagi program from command line 

### ISSUE THREAD

**Issue by marceloubuntu** [hfiref0x/UACME#72]
I want to have a program that no accept arguments when you execute it from the command line, may you tell me where should I edit it to stop getting those options from 1 to 59.

For example I would like to run the program like this,
Akagi64.exe

So Then I will add faction to verify which Operating System is running and it will try all possible methods without user select the method.

**Comment by hfiref0x** [comment]
```
@echo off
set count=1
:loop
echo Run akagi64
echo %count%
set /a count=count+1
if %count%==60 goto exitloop
goto loop
:exitloop
pause
```

**Comment by marcelloubuntu** [comment]
Please may you tell me where should I find it...
@echo off
set count=1
:loop
echo Run akagi64
echo %count%
akagi64 %count%
set /a count=count+1
if %count%==60 goto exitloop
goto loop
:exitloop
pause

**Comment by hfiref0x** [comment]
It is a batch file.

**Comment by marcelloubuntu** [comment]
would you mind to send me a screenshot?

**Comment by hfiref0x** [comment]
Screenshot of what? Batch file? Copy this text to new file and rename it to my.bat

**Comment by marceloubuntu** [comment]
Thanks 🙏 for your patience,It's working. Is this the only way?

**Comment by hfiref0x** [comment]
Of course not.
