### ISSUE TITLE
Is it possible to make it 

### ISSUE THREAD

**Issue by classworks** [hfiref0x/UACME#75]
Hello brother !
I have found you on HF.Can you make it UAC Bypass just single click no popup.I mean It will be able to get Admin privilege with out clicking on yes/no prompt ?

Thanks

**Comment by hfiref0x** [comment]
I've no idea what HF mean. If it infamous "hackforums" then you cannot find me there, because I never registered on it. Your suggestion is out of purpose of this tool.
