### ISSUE TITLE
method 33 - popup box

### ISSUE THREAD

**Issue by crimsoncore** [hfiref0x/UACME#76]
when running this you get a popup asking yes/no depending on which way you want to run this - would it be possible to do this as a cmd-line parameter or just define 2 methods. Just a matter of not showing the popup?

Many Thanks,
L.

**Comment by hfiref0x** [comment]
Why is that important to you?

**Comment by crimsoncore** [comment]
when you're demonstrating these bypasses you don't want user interaction

**Comment by hfiref0x** [comment]
Ok, I will look what I can do.

**Comment by crimsoncore** [comment]
cool! nice tool by the way
