### ISSUE TITLE
admin account with limited access required 

### ISSUE THREAD

**Issue by deadmans96** [hfiref0x/UACME#8]
this message popup when I tried to test a test account with specified privileges

**Comment by AdLindsay** [comment]
It's quite self-explanatory, you need to be using an account with administrative privileges. The account you used to run it was just a standard account.

**Comment by hfiref0x** [comment]
System Requirements

    x86-32/x64 Windows 7/8/8.1/10TH1/10TH2/10RS1 (client, some methods however works on server version too).
    Admin account with UAC set on default settings required.
