### ISSUE TITLE
Compilation issue (STATUS_UNSATISFIED_DEPENDENCIES)

### ISSUE THREAD

**Issue by brn7331** [hfiref0x/UACME#83]
Hi, 

I'm trying to compile the source using Visual Studio 2019 on win10, SDK 10.0.18362.0 and Toolset v142, but when compiling I receive the following error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'STATUS_UNSATISFIED_DEPENDENCIES': undeclared identifier	Akagi	C:\Users\lol\Downloads\UACME-master\Source\Akagi\methods\hybrids.c	1202	
Error	C2065	'STATUS_UNSATISFIED_DEPENDENCIES': undeclared identifier	Akagi	C:\Users\lol\Downloads\UACME-master\Source\Akagi\methods\api0cradle.c	48	
```
Do you have any idea why?
Thanks!

**Comment by hfiref0x** [comment]
For some reason your ntstatus.h is missing this declaration. Install 19041 SDK and try again.

**Comment by brn7331** [comment]
Installing 19041 SDK solved it, thanks!

**Comment by hfiref0x** [comment]
That seems this declaration is only available starting from 19041 SDK. I'll fix that in code, thanks for report.
