### ISSUE TITLE
UAC bypass with Internet Explorer add-on Installer abuse

### ISSUE THREAD

**Issue by AzAgarampur** [hfiref0x/UACME#85]
Hello,

I would like to help contribute once again. Are you willing to take a look? If yes, I'll describe the method and provide the code.

Thank you.

**Comment by hfiref0x** [comment]
Hello,

sure.

**Comment by AzAgarampur** [comment]
Ok, thanks for the reply.

This is a new method which abuses an auto-elevated COM interface. The COM interface is the internet explorer add-on installer. The interface allows us to call `CreateProcessW` from the elevated DCOM server `ieinstal.exe`. My example uses it and simply runs `cmd.exe` as admin.

Here is the code: [](https://github.com/AzAgarampur/byeintegrity2-uac)

**Comment by hfiref0x** [comment]
What is the preconditions for this method? I see you use IFileOperation.

**Comment by hfiref0x** [comment]
Aren't it possible to hijack this `bdeunlock.exe` dependencies by placing your fake dll into that cache folder? For example FveApi.dll

> Perhaps we can use custom exe payload, or even a batch file. It can then launch something else if desired. After all, we are able to pass a command line to the program being launched from RunSetupCommand.

I will look on this later today.

**Comment by AzAgarampur** [comment]
> Aren't it possible to hijack this bdeunlock.exe dependencies by placing your fake dll into that cache folder? For example FveApi.dll

Sure, that should work as well.

**Comment by hfiref0x** [comment]
> Perhaps we can use custom exe payload, or even a batch file. It can then launch something else if desired. After all, we are able to pass a command line to the program being launched from RunSetupCommand

It seems that RunSetupCommand code doesn't like command line if it contain "\" in it.

For example 
RunSetupCommand(C:\Temp\IDC6.tmp\[1]ScriptRunner.exe -appvscript cmd.exe) - success launch
RunSetupCommand(C:\Temp\IDC6.tmp\[1]ScriptRunner.exe -appvscript c:\windows\system32\cmd.exe) - E_ACCESSDENIED

**Comment by hfiref0x** [comment]
It seems changing backslash to forward slash solved this problem. Still need some tests to figure out range of working NT versions.

**Comment by AzAgarampur** [comment]
> Also I've a question about VerifyFile. Do you have any idea how to force it check files which are signed through catalog and do not have embedded certificate? This limits number of possible targets (lolbins whatever) that can be used with this method.

I'm not really sure. The structure that is set up by VerifyTrust sets the `WINTRUST_DATA` `UnionChoice` to `WTD_CHOICE_FILE` and uses file. The provider GUID also checks embedded certificate. I don't think we can pass any data to `VerifyTrust` that can change these values for us.

> It seems that RunSetupCommand code doesn't like command line if it contain "\" in it.

Yeah, there are some checks done in `RunSetupCommand` to the path and when extra `\` are found after main exe in path, status is set to access denied and it immediately returns.

> scriptrunner.exe lolbin I use is not present on win7 and win8/8.1, it seems it is only win10 (17763,18363, 19041 present).

For me scriptrunner is not in any system directory. It's only in C:\Windows\servicing and C:\Windows\WinSxS, I'm on 19041. We can still use other dll hijack for existing binary. Or if you find a binary (preferably from Windows 7), that will work as well.

**Comment by hfiref0x** [comment]
That seems scriptrunner is a part of Microsoft Application Virtualization component. I'm using Enterprise/Pro versions of Windows 10 thats probably why I have it installed. Then we need something with embedded certificate that is capable of executing commands and present on Win7/8/8.1. I leave dll hijack as last option here.

**Comment by AzAgarampur** [comment]
I know I said that copying binaries directly will break somethings, but how about doing this: we can copy `cmd.exe` into cache directory with cache name, then use `/C cmd.exe` switch to open up normal command prompt? We can also use other program this way as well, ex, `/C calc.exe` or `/C C:/Windows/System32/notepad.exe`?

**Comment by AzAgarampur** [comment]
The code in the repo now uses the above method. It seems to work pretty well.

**Comment by hfiref0x** [comment]
I just dropped Fubuki as launcher replacing file in cache and it seems work on win7 now. If no bugs revealed I will release this on Monday, thanks for collaboration!

**Comment by AzAgarampur** [comment]
Awesome, I'll be looking forward to it. Thanks so much!

One thing I just want to mention: on line 1703 of hybrids.c, I think the `GetDesktopWindow()` should be `INVALID_HANDLE_VALUE`. HWND parameter is passed to `WinVerifyTrust`, and according to documentation, it states that if HWND is `INVALID_HANDLE_VALUE`, then:

> There is no interactive user. The trust provider performs the verification action without the user's assistance.

Just a suggestion.

**Comment by hfiref0x** [comment]
Done.
