### ISSUE TITLE
Question: why schtasks.exe in method 34 can't run windows service?

### ISSUE THREAD

**Issue by byehack** [hfiref0x/UACME#89]
when we bypassed uac using method 34 then we can't creating windows service. but in other methods this would be possible.

**Comment by hfiref0x** [comment]
Method 34 does not use schtasks. If you mean old versions like 3.2 and below then your question requires more information of what you want to do and how you do this.

**Comment by byehack** [comment]
i mean this version:(using svchost.exe to run schtasks.exe)
![image](https://user-images.githubusercontent.com/26390254/99896582-22cdb800-2ca7-11eb-9622-9a55f02957d6.png)


actually this method is same as [WinPwnage](https://github.com/rootm0s/WinPwnage) uac4 method.

i tried with WinPwnage uac4 to run a windows process that should running in session 0.
i used WinPwnage elevate6 (creating winservice to run process in session 0).
but it seems it can't running process in session 0.

next i investigate about that.
then i tried other uac bypasses in WinPwnage. all of other supported uac bypass could run as session0.
for example here is the difference between "C:\Windows\System32\cmd.exe" ran as uac4(left) and uac10(right):
![image](https://user-images.githubusercontent.com/26390254/99896716-78ef2b00-2ca8-11eb-8c75-04bfd20acc02.png)

**Comment by byehack** [comment]
## Perfomance:
![image](https://user-images.githubusercontent.com/26390254/99897020-13506e00-2cab-11eb-9bac-30ec2942550b.png)

## Job:
![image](https://user-images.githubusercontent.com/26390254/99897044-4e52a180-2cab-11eb-8e3f-c38ee8a6d87d.png)

## Environment:

**Comment by byehack** [comment]
i found the problem.
as you see the `windir` value in environment is changing during bypassing. so we should change the value on new spawned process after bypass.
some works (like evelate to SYSTEM) need `windir` environment. so if its value was wrong that work can't run.
also other difference like `ProgramFiles` environment value can be solve with [disable file system redirect](https://docs.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-wow64disablewow64fsredirection).
