### ISSUE TITLE
UAC bypass with Shell protocol "ms-settings" hijack and fodhelper.exe as trigger

### ISSUE THREAD

**Issue by AzAgarampur** [hfiref0x/UACME#91]
Hey there,

I've got a really simple method that I think would be cool to have in UACMe. All it does is hijack the user association for the protocol `ms-settings` and then run `fodhelper.exe`. I think this should work from all Win 10 from initial release to latest, but I've only developed/tested this on 19042. Here's the code if you wanna take a look: https://github.com/AzAgarampur/byeintegrity-lite

**Comment by hfiref0x** [comment]
Hello,

as I remember original fodhelper method is well signatured by various AV's. Have you saw any reaction from WD/whatever AV on this derivative? I'll look on your implementation tomorrow.

**Comment by AzAgarampur** [comment]
I ran this with WD with realtime protection enabled and no detection. Also ran this with realtime protection with MalwareBytes and no detection.

**Comment by hfiref0x** [comment]
It is working well on 18363/19041/19042/20270.

**Comment by hfiref0x** [comment]
Moved this to master. Thanks for the new method and happy new year!

**Comment by AzAgarampur** [comment]
I wish you a happy new year as well!
