### ISSUE TITLE
supFindUserAssocSet not working anymore on 19041

### ISSUE THREAD

**Issue by h1k421** [hfiref0x/UACME#92]
Hey there,

I recently applied some updates on my 19041 install and ``supFindUserAssocSet`` cannot find ``UserAssocSet_19041`` pattern anymore.

After some researches, I figured out that shell32.dll got updated and that ``UserAssocSet_19042`` pattern work just fine if used.
As such, I think that the code could be updated to try to find the other pattern as well if it cannot be found on 19041.

**Comment by hfiref0x** [comment]
Hello, which exact version of Windows you have  (ver command) and that shell32 version too?

**Comment by h1k421** [comment]
> Hello, which exact version of Windows you have (ver command) and that shell32 version too?

19041.685 for Windows and 19041.662 for shell32.dll

**Comment by hfiref0x** [comment]
Okay I will look on this.

**Comment by h1k421** [comment]
Thanks for your work again and happy new year ^^
